classDiagram

class PresentationLayer {
    <<Interface>>
    +UserController
    +PlaceController
    +AmenityController
    +ReviewController
}

class Facade {
    +HBnBFacade
}

class BusinessLogicLayer {
    +UserModel
    +PlaceModel
    +AmenityModel
    +ReviewModel
}

class PersistenceLayer {
    +Repository
    +InMemoryStorage
}

PresentationLayer --> Facade : calls
Facade --> BusinessLogicLayer : uses models & rules
Facade --> PersistenceLayer : CRUD operations
PersistenceLayer --> InMemoryStorage : store data
