classDiagram

class PresentationLayer {
  API
  Services
}

class Facade {
  HBnBFacade
}

class BusinessLogicLayer {
  Models
  BusinessRules
}

class PersistenceLayer {
  Repositories
  Storage
}

PresentationLayer --> Facade : calls
Facade --> BusinessLogicLayer : uses
Facade --> PersistenceLayer : CRUD
